# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 15:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('is_point', models.BooleanField(default=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('description', models.TextField(blank=True, max_length=4194304, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('permissions', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('mime_type', models.CharField(max_length=1024)),
                ('content_file', models.FileField(upload_to='plan_overlays')),
                ('location', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('value', models.TextField(max_length=1048576)),
                ('priority', models.IntegerField(default=0)),
                ('type', models.CharField(default='text', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PlanOverlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('overlay_background', models.FileField(upload_to='plan_overlays')),
                ('center_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('scale', models.FloatField(default=1.0)),
                ('rotation', models.FloatField(default=0.0)),
                ('z_index', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='SitePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('location', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='planoverlay',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='map_app.SitePlan'),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='map_app.SitePlan'),
        ),
        migrations.AddField(
            model_name='areaofinterest',
            name='attachments',
            field=models.ManyToManyField(related_name='attachments', to='map_app.MediaAttachment'),
        ),
        migrations.AddField(
            model_name='areaofinterest',
            name='overlay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_of_interest', to='map_app.SitePlan'),
        ),
    ]
