# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 16:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('secret', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('value', models.TextField(max_length=1048576)),
                ('priority', models.IntegerField(default=0)),
                ('type', models.CharField(default='text', max_length=1024)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workers_app.Worker')),
            ],
        ),
    ]
